Add mainnet solver rewards dashboard and update with service fee
cowprotocol/dune-queries pull request #8
Opened 2024-09-02 22:27 UTC by harisang

This PR adds the following to the repo:
- [Query 2510345](https://dune.com/queries/2510345), which is the main query showing in the solver rewards [dashboard](https://dune.com/cowprotocol/cow-solver-rewards?StartTime=2024-08-20+00%3A00%3A00&EndTime=2024-08-27+00%3A00%3A00).
- [Query 4017925](https://dune.com/queries/4017925), which computes whether a solver needs to pay the CoW DAO bonding pool service fee or not.

Note that query 2510345 has some proposed changes, regarding the implementation of the service fee and the reduction in the rewards being transferred to solvers. So the plan is to get the PR approved, and before merging actually edit query 2510345 to ensure its code is identical to the code in this PR.

2024-09-03 10:10 UTC, fhenneke requested changes
This is a good opportunity to clean up this query (and the respective solver-rewards query).

As a minimum, the external queries referenced in this query should be called instead of their code being copied.

There is much room for other improvements, but some of that (e.g. using the actual solver-rewards query for the dashboard or using query 4021306 from coincidence of want for slippage) could be addressed later.

2024-09-03 10:10 UTC, fhenneke commented on mainnet_solver_rewards/service_fee_query_4017925.sql
> +    date_diff('day', date(jd.joined_on), date(NOW())) AS days_in_pool
`NOW()` should probably be changed to a `cutoff_time` parameter which would chosen as `start_time`.

2024-09-03 10:10 UTC, fhenneke commented on mainnet_solver_rewards/service_fee_query_4017925.sql
> +initial_vouches AS (
The part on vouches might just reuse the vouches query.

2024-09-03 10:10 UTC, fhenneke commented on mainnet_solver_rewards/service_fee_query_4017925.sql
That query does not look much simpler that just hard-coding all solver addresses, their starting date, and their status (e.g. exempt for 6 month, 9 month, indefinitely).

The query might help finding those dates.

2024-09-03 10:10 UTC, fhenneke commented on mainnet_solver_rewards/service_fee_query_4017925.sql
> +  SELECT from_hex(pool), name, from_hex(funder) FROM (
(this query uses a different style (keywords in all caps) than the other query)

2024-09-03 18:56 UTC, fhenneke approved these changes

2024-09-16 09:53 UTC, harisang commented
Closing as a lot of changes have happened in between so will reopen a PR with just the main dashboard there.

2024-09-16 09:53 UTC, closed without merging